// Auto-generated file. Do not edit manually.
// Generated by Scripts/w3c/generate-w3c-tests.sh
import Foundation
import XCTest
@testable import SVGSwiftUI

final class W3CGeneratedTests: XCTestCase {
    private enum FixtureMode: String {
        case parse
        case render
    }

    private enum ExpectedResult: String {
        case pass
        case fail
        case unsupported
    }

    private struct FixtureExpectation {
        let id: String
        let mode: FixtureMode
        let expected: ExpectedResult
        let svgPath: String
        let referencePath: String
        let unsupportedFeatureKeys: [String]
    }

    private enum FixtureError: Error {
        case missingResource(String)
    }

    func testW3CGeneratedSuite() throws {
        XCTAssertFalse(__fixtures().isEmpty)
        for fixture in __fixtures() {
            try assertW3CFixture(fixture)
        }
    }

    private func __fixtures() -> [FixtureExpectation] {
        return [
            FixtureExpectation(
                id: "w3c-1.1F2-coords-skew-transform",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/coords-skew-transform.svg",
                referencePath: "fixtures/1.1F2/ref/coords-skew-transform.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-filters-blend-01-b-min",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/filters-blend-01-b-min.svg",
                referencePath: "fixtures/1.1F2/ref/filters-blend-01-b-min.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-filters-chain-01-b-min",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/filters-chain-01-b-min.svg",
                referencePath: "fixtures/1.1F2/ref/filters-chain-01-b-min.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-filters-colormatrix-01-b-min",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/filters-colormatrix-01-b-min.svg",
                referencePath: "fixtures/1.1F2/ref/filters-colormatrix-01-b-min.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-filters-composite-arithmetic-01-b-min",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/filters-composite-arithmetic-01-b-min.svg",
                referencePath: "fixtures/1.1F2/ref/filters-composite-arithmetic-01-b-min.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-paths-move-line",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/paths-move-line.svg",
                referencePath: "fixtures/1.1F2/ref/paths-move-line.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-shapes-rect-circle",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/shapes-rect-circle.svg",
                referencePath: "fixtures/1.1F2/ref/shapes-rect-circle.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-shapes-rounded-rect",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/shapes-rounded-rect.svg",
                referencePath: "fixtures/1.1F2/ref/shapes-rounded-rect.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-styling-fillrule-dash",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/styling-fillrule-dash.svg",
                referencePath: "fixtures/1.1F2/ref/styling-fillrule-dash.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.1F2-styling-stroke-capjoin",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.1F2/svg/styling-stroke-capjoin.svg",
                referencePath: "fixtures/1.1F2/ref/styling-stroke-capjoin.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.2T-coords-relative-transform",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.2T/svg/coords-relative-transform.svg",
                referencePath: "fixtures/1.2T/ref/coords-relative-transform.expected.txt",
                unsupportedFeatureKeys: []
            ),
            FixtureExpectation(
                id: "w3c-1.2T-styling-fill-stroke",
                mode: .parse,
                expected: .pass,
                svgPath: "fixtures/1.2T/svg/styling-fill-stroke.svg",
                referencePath: "fixtures/1.2T/ref/styling-fill-stroke.expected.txt",
                unsupportedFeatureKeys: []
            ),
        ]
    }

    private func assertW3CFixture(_ fixture: FixtureExpectation) throws {
        let fixtureURL: URL = try w3cResourceURL(fixture.svgPath)
        let data: Data = try Data(contentsOf: fixtureURL)
        let parser: SVGParser = SVGParser()
        let metadata: [String: String] = loadMetadata(for: fixture.referencePath)
        let referenceMode: String? = metadata["mode"]
        let expectedNodeCount: Int? = metadata["nodeCount"].flatMap(Int.init)

        switch fixture.expected {
        case .pass:
            let document = try parser.parse(data: data)
            if let expectedMode = referenceMode {
                XCTAssertEqual(expectedMode, fixture.mode.rawValue)
            }
            if let expectedNodeCount {
                XCTAssertEqual(document.nodes.count, expectedNodeCount)
            }
        case .unsupported:
            let document = try parser.parse(data: data)
            if let expectedMode = referenceMode {
                XCTAssertEqual(expectedMode, fixture.mode.rawValue)
            }
            if let expectedNodeCount {
                XCTAssertEqual(document.nodes.count, expectedNodeCount)
            }
            if fixture.unsupportedFeatureKeys.isEmpty {
                XCTAssertFalse(document.unsupportedFeatures.isEmpty)
            } else {
                for key in fixture.unsupportedFeatureKeys {
                    XCTAssertGreaterThan(document.unsupportedFeatures[key, default: 0], 0)
                }
            }
        case .fail:
            XCTAssertThrowsError(try parser.parse(data: data))
        }
    }

    private func w3cResourceURL(_ resourcePath: String) throws -> URL {
        let resourcePathComponents = resourcePath.split(separator: "/")
        guard let resourceName = resourcePathComponents.last else {
            throw FixtureError.missingResource(resourcePath)
        }
        let resourceBase = String(resourceName)
        guard let dotIndex = resourceBase.lastIndex(of: ".") else {
            throw FixtureError.missingResource(resourcePath)
        }
        let name = String(resourceBase[..<dotIndex])
        let extensionStart = resourceBase.index(after: dotIndex)
        let fileExtension = String(resourceBase[extensionStart...])
        guard let fixtureURL = Bundle.module.url(
            forResource: name,
            withExtension: fileExtension
        ) else {
            throw FixtureError.missingResource(resourcePath)
        }
        return fixtureURL
    }

    private func loadMetadata(for resourcePath: String) -> [String: String] {
        let trimmedPath = resourcePath.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedPath.isEmpty {
            return [:]
        }
        do {
            let metadataURL = try w3cResourceURL(trimmedPath)
            let metadataText = try String(contentsOf: metadataURL, encoding: .utf8)
            var output: [String: String] = [:]
            let rows = metadataText.split(whereSeparator: \.isNewline)
            for row in rows {
                let line = row.trimmingCharacters(in: .whitespacesAndNewlines)
                if line.isEmpty || line.hasPrefix("#") {
                    continue
                }
                let parts = line.split(separator: "=", maxSplits: 1)
                if parts.count == 2 {
                    output[String(parts[0])] = String(parts[1])
                }
            }
            return output
        } catch {
            return [:]
        }
    }
}
