#!/usr/bin/env bash
set -euo pipefail

MANIFEST=${1:-}
OUTPUT=${2:-}

if [[ -z "$MANIFEST" || -z "$OUTPUT" ]]; then
  cat <<USAGE
Usage: ./Scripts/w3c/generate-w3c-tests.sh <manifest-path> <output-path>

Examples:
  ./Scripts/w3c/generate-w3c-tests.sh Tests/SVGSwiftUITests/W3C/w3c-manifest.json Tests/SVGSwiftUITests/W3CGeneratedTests.swift
USAGE
  exit 1
fi

if [[ ! -f "$MANIFEST" ]]; then
  echo "Manifest file not found: $MANIFEST" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required by this generator." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

python3 - "$MANIFEST" "$OUTPUT" <<'PY'
import json
import pathlib
import sys

manifest_path = pathlib.Path(sys.argv[1])
output_path = pathlib.Path(sys.argv[2])

with manifest_path.open("r", encoding="utf-8") as handle:
    manifest = json.load(handle)

fixtures = manifest.get("fixtures", [])


def normalize_mode(value: str) -> str:
    normalized = str(value or "parse").lower()
    if normalized not in {"parse", "render"}:
        return "parse"
    return normalized


def normalize_expected(value: str) -> str:
    normalized = str(value or "pass").lower()
    if normalized not in {"pass", "fail", "unsupported"}:
        return "unsupported"
    return normalized


def normalize_unsupported_features(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    output: list[str] = []
    for item in value:
        text = str(item).strip()
        if text:
            output.append(text)
    return output


def quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f"\"{escaped}\""


def quote_string_list(values: list[str]) -> str:
    items = ", ".join(quote(value) for value in values)
    return f"[{items}]"


fixtures = sorted(fixtures, key=lambda item: (str(item.get("suite", "")), str(item.get("id", ""))))

lines = []
lines.append("// Auto-generated file. Do not edit manually.\n")
lines.append("// Generated by Scripts/w3c/generate-w3c-tests.sh\n")
lines.append("import Foundation\n")
lines.append("import XCTest\n")
lines.append("@testable import SVGSwiftUI\n")
lines.append("\n")
lines.append("final class W3CGeneratedTests: XCTestCase {\n")
lines.append("    private enum FixtureMode: String {\n")
lines.append("        case parse\n")
lines.append("        case render\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    private enum ExpectedResult: String {\n")
lines.append("        case pass\n")
lines.append("        case fail\n")
lines.append("        case unsupported\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    private struct FixtureExpectation {\n")
lines.append("        let id: String\n")
lines.append("        let mode: FixtureMode\n")
lines.append("        let expected: ExpectedResult\n")
lines.append("        let svgPath: String\n")
lines.append("        let referencePath: String\n")
lines.append("        let unsupportedFeatureKeys: [String]\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    private enum FixtureError: Error {\n")
lines.append("        case missingResource(String)\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    func testW3CGeneratedSuite() throws {\n")
lines.append("        XCTAssertFalse(__fixtures().isEmpty)\n")
lines.append("        for fixture in __fixtures() {\n")
lines.append("            try assertW3CFixture(fixture)\n")
lines.append("        }\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    private func __fixtures() -> [FixtureExpectation] {\n")
lines.append("        return [\n")

for index, item in enumerate(fixtures):
    fixture_id = str(item.get("id", f"fixture-{index}"))
    mode = normalize_mode(item.get("mode", "parse"))
    expected = normalize_expected(item.get("expected", "pass"))
    svg = str(item.get("svg", ""))
    reference = str(item.get("reference", ""))
    unsupported_feature_keys = normalize_unsupported_features(
        item.get("unsupportedFeatures", [])
    )
    lines.append("            FixtureExpectation(\n")
    lines.append(f"                id: {quote(fixture_id)},\n")
    lines.append(f"                mode: .{mode},\n")
    lines.append(f"                expected: .{expected},\n")
    lines.append(f"                svgPath: {quote(svg)},\n")
    lines.append(f"                referencePath: {quote(reference)},\n")
    lines.append(
        f"                unsupportedFeatureKeys: {quote_string_list(unsupported_feature_keys)}\n"
    )
    lines.append("            ),\n")

lines.append("        ]\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    private func assertW3CFixture(_ fixture: FixtureExpectation) throws {\n")
lines.append("        let fixtureURL: URL = try w3cResourceURL(fixture.svgPath)\n")
lines.append("        let data: Data = try Data(contentsOf: fixtureURL)\n")
lines.append("        let parser: SVGParser = SVGParser()\n")
lines.append("        let metadata: [String: String] = loadMetadata(for: fixture.referencePath)\n")
lines.append("        let referenceMode: String? = metadata[\"mode\"]\n")
lines.append("        let expectedNodeCount: Int? = metadata[\"nodeCount\"].flatMap(Int.init)\n")
lines.append("\n")
lines.append("        switch fixture.expected {\n")
lines.append("        case .pass:\n")
lines.append("            let document = try parser.parse(data: data)\n")
lines.append("            if let expectedMode = referenceMode {\n")
lines.append("                XCTAssertEqual(expectedMode, fixture.mode.rawValue)\n")
lines.append("            }\n")
lines.append("            if let expectedNodeCount {\n")
lines.append("                XCTAssertEqual(document.nodes.count, expectedNodeCount)\n")
lines.append("            }\n")
lines.append("        case .unsupported:\n")
lines.append("            let document = try parser.parse(data: data)\n")
lines.append("            if let expectedMode = referenceMode {\n")
lines.append("                XCTAssertEqual(expectedMode, fixture.mode.rawValue)\n")
lines.append("            }\n")
lines.append("            if let expectedNodeCount {\n")
lines.append("                XCTAssertEqual(document.nodes.count, expectedNodeCount)\n")
lines.append("            }\n")
lines.append("            if fixture.unsupportedFeatureKeys.isEmpty {\n")
lines.append("                XCTAssertFalse(document.unsupportedFeatures.isEmpty)\n")
lines.append("            } else {\n")
lines.append("                for key in fixture.unsupportedFeatureKeys {\n")
lines.append("                    XCTAssertGreaterThan(document.unsupportedFeatures[key, default: 0], 0)\n")
lines.append("                }\n")
lines.append("            }\n")
lines.append("        case .fail:\n")
lines.append("            XCTAssertThrowsError(try parser.parse(data: data))\n")
lines.append("        }\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    private func w3cResourceURL(_ resourcePath: String) throws -> URL {\n")
lines.append("        let resourcePathComponents = resourcePath.split(separator: \"/\")\n")
lines.append("        guard let resourceName = resourcePathComponents.last else {\n")
lines.append("            throw FixtureError.missingResource(resourcePath)\n")
lines.append("        }\n")
lines.append("        let resourceBase = String(resourceName)\n")
lines.append("        guard let dotIndex = resourceBase.lastIndex(of: \".\") else {\n")
lines.append("            throw FixtureError.missingResource(resourcePath)\n")
lines.append("        }\n")
lines.append("        let name = String(resourceBase[..<dotIndex])\n")
lines.append("        let extensionStart = resourceBase.index(after: dotIndex)\n")
lines.append("        let fileExtension = String(resourceBase[extensionStart...])\n")
lines.append("        guard let fixtureURL = Bundle.module.url(\n")
lines.append("            forResource: name,\n")
lines.append("            withExtension: fileExtension\n")
lines.append("        ) else {\n")
lines.append("            throw FixtureError.missingResource(resourcePath)\n")
lines.append("        }\n")
lines.append("        return fixtureURL\n")
lines.append("    }\n")
lines.append("\n")
lines.append("    private func loadMetadata(for resourcePath: String) -> [String: String] {\n")
lines.append("        let trimmedPath = resourcePath.trimmingCharacters(in: .whitespacesAndNewlines)\n")
lines.append("        if trimmedPath.isEmpty {\n")
lines.append("            return [:]\n")
lines.append("        }\n")
lines.append("        do {\n")
lines.append("            let metadataURL = try w3cResourceURL(trimmedPath)\n")
lines.append("            let metadataText = try String(contentsOf: metadataURL, encoding: .utf8)\n")
lines.append("            var output: [String: String] = [:]\n")
lines.append("            let rows = metadataText.split(whereSeparator: \\.isNewline)\n")
lines.append("            for row in rows {\n")
lines.append("                let line = row.trimmingCharacters(in: .whitespacesAndNewlines)\n")
lines.append("                if line.isEmpty || line.hasPrefix(\"#\") {\n")
lines.append("                    continue\n")
lines.append("                }\n")
lines.append("                let parts = line.split(separator: \"=\", maxSplits: 1)\n")
lines.append("                if parts.count == 2 {\n")
lines.append("                    output[String(parts[0])] = String(parts[1])\n")
lines.append("                }\n")
lines.append("            }\n")
lines.append("            return output\n")
lines.append("        } catch {\n")
lines.append("            return [:]\n")
lines.append("        }\n")
lines.append("    }\n")
lines.append("}\n")

output_path.write_text("".join(lines), encoding="utf-8")
print(f"Generated {len(fixtures)} fixtures -> {output_path}")
PY
